### PR TITLE
Adding LADDER

### PR DESCRIPTION
**Pull request by rahulshah1397**
LADDER is a deep learning framework for reconstructing (possibly correlated) sequential cosmological data with corresponding covariance information, to accurately predict both mean values and uncertainties.

The code and its first application has been demonstrated in [Shah et al. 2024](https://doi.org/10.3847/1538-4365/ad5558) ([arXiv:2401.17029](https://www.arxiv.org/abs/2401.17029)).

The main GitHub repository is located here: [https://github.com/rahulshah1397/LADDER](https://github.com/rahulshah1397/LADDER).

The corresponding Zenodo record is here: [10.5281/zenodo.11175054](https://zenodo.org/doi/10.5281/zenodo.11175054).

There also exists an ASCL entry: [ASCL:2408.007](https://ascl.net/2408.007).

### CODE REVIEW

**Review by lonbar — CHANGES_REQUESTED** [review]
Thanks for your contribution! You haven't added your Zenodo and ASCL entries in LADDER's description in the README. Please add them, because otherwise it will be difficult to find them once the changes have been merged.

**Comment by rahulshah1397** [comment]
> Thanks for your contribution! You haven't added your Zenodo and ASCL entries in LADDER's description in the README. Please add them, because otherwise it will be difficult to find them once the changes have been merged.

Thank you for the suggestion! I have made the changes, kindly advise if it is okay now.

**Review by lonbar — APPROVED** [review]
Looks good to me. Thanks again!

**Comment by rahulshah1397** [comment]
> Looks good to me. Thanks again!

Thank you for your prompt review and assistance!

**Pull request merged**
