### PR TITLE
Added CompOSE

### PR DESCRIPTION
**Pull request by jorgetc16**
Hi Niko,
I just added CompOSE code to the astro part. It gives you interpolation tables of the relevant thermodynamical quantities for several equation of states. It can be used for CC-SN, cold neutron stars, neutron star mergers, etc.
Cheers,
Jorge

### CODE REVIEW

**Comment by nikosarcevic** [comment]
> 

Oh this is amazing, Thank you so much!

I need to do a bit of housekeeping here for sure

**Comment by jorgetc16** [comment]
No problem, I will check during this week if more codes that I know are there and if not I'll add them. :)

**Comment by nikosarcevic** [comment]
> No problem, I will check during this week if more codes that I know are there and if not I'll add them. :)

You are the best. Btw I know it might be too much to ask but do you maybe have the time to meet on zoom and help me out sorting thru stuff? No pressure of course

**Comment by jorgetc16** [comment]
Sure, I started using github a few months ago and I don't have a broad knowledge of codes but I am happy to help as much as I can.

**Comment by nikosarcevic** [comment]
> Sure, I started using github a few months ago and I don't have a broad knowledge of codes but I am happy to help as much as I can.

no problem. what is your availability this week? I am free on Thursday and on the weekend.

**Comment by jorgetc16** [comment]
Hi Niko, sorry I just saw it. Today I can from 15 to 16 (uk time) or tomorrow but I think tomorrow doesn't work for you, right?. On the weekend maybe saturday afternoon. Please answer me by mail at jorgetc@iac.es

**Comment by nikosarcevic** [comment]
no problem. yes we can meet today whenever
tomorrow I can only late in the afternoon (and even that is maybe as I have some workshop at uni)

**Comment by nikosarcevic** [comment]
> Hi Niko, sorry I just saw it. Today I can from 15 to 16 (uk time) or tomorrow but I think tomorrow doesn't work for you, right?. On the weekend maybe saturday afternoon. Please answer me by mail at [jorgetc@iac.es](mailto:jorgetc@iac.es)

btw here is my phone number add me on WhatsApp. once you add me ill remove it from here

+447306126057

**Pull request merged**
